# Generated by Django 5.1.6 on 2025-02-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloge', '0006_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
